// Headless controller checks; these do not replace visual browser verification.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import * as galaxy from '../src/galaxy.js';
import * as config from '../src/config.js';
import * as engine from '../src/engine.js';
import * as storage from '../src/storage.js';
import {CloudConflict} from '../src/cloud.js';
function ui(){const mem=new Map(),app={innerHTML:'',addEventListener(){}},toast={classList:{add(){},remove(){}}};let dialog=null;const doc={getElementById:id=>id==='app'?app:id==='toast'?toast:null,querySelector:()=>dialog,querySelectorAll:()=>[],addEventListener(){},createElement:()=>({innerHTML:'',addEventListener(){},showModal(){},remove(){dialog=null;}}),body:{append(d){dialog=d;}}};const store={getItem:k=>mem.get(k)||null,setItem:(k,v)=>mem.set(k,v),removeItem:k=>mem.delete(k)};const deps={...galaxy,...config,...engine,...storage,loadGame:(s=store,key=storage.SAVE_KEY)=>storage.loadGame(s,key),CloudConflict,CLOUD_CONFIG:{enabled:false},connectCloud:async()=>null,document:doc,localStorage:store,navigator:{},window:{addEventListener(){}},setInterval(){},setTimeout(){},clearTimeout(){},confirm:()=>true};const source=readFileSync('src/app.js','utf8').replace(/^import .*;$/gm,'');const controller=new Function(...Object.keys(deps),source+'\nreturn {loadAccount,flushCloud,logoutAccount,refreshGalaxy,launchGalaxy,galaxy,command,refreshRanking,leaderboard,clearRanking,get state(){return state;},get galaxyData(){return galaxyData;},get galaxyBusy(){return galaxyBusy;},showGalaxy(){galaxySection="shared";},get blocked(){return cloudBlocked;},attach(c){cloud=c;},get dialog(){return document.querySelector("dialog");}};')(...Object.values(deps));return {controller,store,app};}
function fakeCloud(remote,revision){return {user:{id:'a',email:'a@test.de'},revision,loaded:true,async load(){return remote;},async save(){this.revision++;return this.revision;},async signOut(){this.user=null;}};}
test('Returning login recovers unsynced local actions when cloud revision is unchanged',async()=>{const {controller:c,store}=ui(),remote=engine.newGame('Remote'),local=engine.newGame('Unsynced');storage.saveGame(local,store,storage.SAVE_KEY+'-account-a');store.setItem(storage.SAVE_KEY+'-account-a-cloud-meta',JSON.stringify({pending:true,revision:3}));c.attach(fakeCloud(remote,3));await c.loadAccount();assert.equal(c.state.name,'Unsynced');assert.equal(c.blocked,false);assert.equal(await c.flushCloud(),true);assert.deepEqual(JSON.parse(store.getItem(storage.SAVE_KEY+'-account-a-cloud-meta')),{pending:false,revision:4});});
test('Diverging account caches stop play until cloud replacement is explicitly selected',async()=>{const {controller:c,store}=ui();storage.saveGame(engine.newGame('Unsynced'),store,storage.SAVE_KEY+'-account-a');store.setItem(storage.SAVE_KEY+'-account-a-cloud-meta',JSON.stringify({pending:true,revision:1}));c.attach(fakeCloud(engine.newGame('Remote newer'),2));await c.loadAccount();assert.equal(c.blocked,true);assert.equal(c.state.name,'Unsynced');await c.loadAccount(true);assert.equal(c.blocked,false);assert.equal(c.state.name,'Remote newer');});
test('Logging out saves account and restores the separate guest world',async()=>{const {controller:c,store}=ui();storage.saveGame(engine.newGame('Guest'),store);const cloud=fakeCloud(engine.newGame('Account'),1);c.attach(cloud);await c.loadAccount();await c.logoutAccount();assert.equal(c.state.name,'Guest');assert.equal(cloud.user,null);assert.equal(storage.loadGame(store).state.name,'Guest');assert.equal(storage.loadGame(store,storage.SAVE_KEY+'-account-a').state.name,'Account');});

test('Ranking escapes commander names and clears cached rows on logout',async()=>{const {controller:c}=ui();const cloud=fakeCloud(engine.newGame('A'),1);cloud.leaderboard=async()=>[{commander:'<img src=x onerror=alert(1)>',rank:1,points:12,building_points:9,research_points:3,fleet_points:0,colonies:0,is_me:true}];c.attach(cloud);await c.loadAccount();await c.refreshRanking(true);assert.ok(c.leaderboard().includes('&lt;img'));assert.ok(!c.leaderboard().includes('<img'));assert.ok(c.leaderboard().includes('· Du'));await c.logoutAccount();const other=fakeCloud(engine.newGame('Other'),1);c.attach(other);assert.ok(!c.leaderboard().includes('&lt;img'));});
test('Late ranking response cannot carry data across account changes',async()=>{const {controller:c}=ui();const cloud=fakeCloud(engine.newGame('A'),1);let resolve;cloud.leaderboard=()=>new Promise(r=>resolve=r);c.attach(cloud);await c.loadAccount();const pending=c.refreshRanking(true);c.clearRanking();c.attach(fakeCloud(engine.newGame('Other'),1));resolve([{commander:'Old Account',rank:1,points:10,building_points:10,research_points:0,fleet_points:0,colonies:0,is_me:true}]);await pending;assert.ok(!c.leaderboard().includes('Old Account'));});
function galaxyReply(){return {start:{x:40,y:500},systems:galaxy.GALAXY_SYSTEMS.map(s=>({...s,planetCount:3})),planets:[{id:'g-helion-p1',system:'helion',slot:1,surveyed:false}],missions:[],serverNow:Date.now()};}
test('Galaxy controller preserves unknown targets, applies authoritative changes and clears data across accounts',async()=>{const {controller:c}=ui(),s=engine.newGame('Galaxie');s.galaxy={x:40,y:500};s.planets[0].ships.longProbe=1;const cloud=fakeCloud(s,1);cloud.galaxyView=async()=>galaxyReply();cloud.galaxySync=async action=>{assert.equal(action.kind,'scan');const next=structuredClone(c.state);next.planets[0].ships.longProbe=0;cloud.revision++;return {state:next,galaxy:{...galaxyReply(),missions:[{id:'m',kind:'scan',from:'home',to:'g-helion-p1',system:'helion',slot:1,start:Date.now(),arrival:Date.now()+10000,due:Date.now()+20000}]}};};c.attach(cloud);await c.loadAccount();await c.refreshGalaxy(true);assert.equal(c.galaxyData.planets[0].surveyed,false);c.showGalaxy();const markup=c.galaxy(c.state.planets[0]);assert.ok(markup.includes('P1 · Unbekannt'));assert.ok(!markup.includes('×undefined'));await c.launchGalaxy('scan','g-helion-p1');assert.equal(c.state.planets[0].ships.longProbe,0);assert.equal(c.galaxyData.missions.length,1);assert.equal(c.galaxyBusy,false);c.clearRanking();assert.equal(c.galaxyData,null);});
test('Late galaxy reply cannot expose surveys from a previous account; errors release the UI lock',async()=>{const {controller:c}=ui(),s=engine.newGame('A');s.galaxy={x:40,y:500};const cloud=fakeCloud(s,1);let resolve;cloud.galaxyView=()=>new Promise(r=>resolve=r);c.attach(cloud);await c.loadAccount();const pending=c.refreshGalaxy(true);c.clearRanking();c.attach(fakeCloud(engine.newGame('B'),1));resolve({...galaxyReply(),planets:[{id:'g-helion-p1',system:'helion',slot:1,surveyed:true,name:'Secret'}]});await pending;assert.equal(c.galaxyData,null);assert.equal(c.galaxyBusy,false);const other=fakeCloud(s,1);other.galaxyView=async()=>{throw Error('network down');};c.attach(other);await c.refreshGalaxy(true);assert.equal(c.galaxyBusy,false);assert.equal(c.galaxyData,null);});
