import * as uiAssets from '../src/ui-assets.js';
// Headless controller checks; these do not replace visual browser verification.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import * as galaxy from '../src/galaxy.js';
import * as config from '../src/config.js';
import * as engine from '../src/engine.js';
import * as storage from '../src/storage.js';
import * as pvp from '../src/pvp-ui.js';
import * as reports from '../src/reports-ui.js';
import {CloudConflict} from '../src/cloud.js';
function ui(FormDataType=globalThis.FormData){const listeners={app:[],document:[]};const mem=new Map(),app={innerHTML:'',addEventListener(type,handler){if(type==='submit')listeners.app.push(handler);}},toast={classList:{add(){},remove(){}}};let dialog=null;const doc={getElementById:id=>id==='app'?app:id==='toast'?toast:null,querySelector:()=>dialog,querySelectorAll:()=>[],addEventListener(type,handler){if(type==='submit')listeners.document.push(handler);},createElement:()=>({innerHTML:'',addEventListener(){},showModal(){},remove(){dialog=null;}}),body:{append(d){dialog=d;}}};const store={getItem:k=>mem.get(k)||null,setItem:(k,v)=>mem.set(k,v),removeItem:k=>mem.delete(k)};const deps={FormData:FormDataType,...uiAssets,...reports,...pvp,...galaxy,...config,...engine,...storage,loadGame:(s=store,key=storage.SAVE_KEY)=>storage.loadGame(s,key),CloudConflict,CLOUD_CONFIG:{enabled:false},connectCloud:async()=>null,document:doc,localStorage:store,navigator:{},window:{addEventListener(){}},setInterval(){},setTimeout(){},clearTimeout(){},confirm:()=>true};const source=readFileSync('src/app.js','utf8').replace(/^import .*;$/gm,'');const controller=new Function(...Object.keys(deps),source+'\nreturn {refreshReports,captureReportUI,get reportData(){return reportData;},get reportOpened(){return reportOpened;},buildings,research,orb,tradeRoutes,shipJobPanel,setRouteView(section,id=0){routeSection=section;routeEditId=id;},setRouteFilter(query,filter){routeQuery=query;routeFilter=filter;},get routeSection(){return routeSection;},loadAccount,flushCloud,logoutAccount,refreshGalaxy,launchGalaxy,galaxy,command,refreshRanking,leaderboard,clearRanking,get state(){return state;},get galaxyData(){return galaxyData;},get galaxyBusy(){return galaxyBusy;},showGalaxy(){galaxySection="shared";},get blocked(){return cloudBlocked;},attach(c){cloud=c;},get dialog(){return document.querySelector("dialog");}};')(...Object.values(deps));return {controller,store,app,doc,async submit(form){const event={target:form,preventDefault(){}};const pending=listeners.app.map(handler=>handler(event));pending.push(...listeners.document.map(handler=>handler(event)));await Promise.all(pending);}};}
function fakeCloud(remote,revision){return {user:{id:'a',email:'a@test.de'},revision,loaded:true,async load(){return remote;},async save(){this.revision++;return this.revision;},async signOut(){this.user=null;}};}
test('Returning login recovers unsynced local actions when cloud revision is unchanged',async()=>{const {controller:c,store}=ui(),remote=engine.newGame('Remote'),local=engine.newGame('Unsynced');storage.saveGame(local,store,storage.SAVE_KEY+'-account-a');store.setItem(storage.SAVE_KEY+'-account-a-cloud-meta',JSON.stringify({pending:true,revision:3}));c.attach(fakeCloud(remote,3));await c.loadAccount();assert.equal(c.state.name,'Unsynced');assert.equal(c.blocked,false);assert.equal(await c.flushCloud(),true);assert.deepEqual(JSON.parse(store.getItem(storage.SAVE_KEY+'-account-a-cloud-meta')),{pending:false,revision:4});});
test('Diverging account caches stop play until cloud replacement is explicitly selected',async()=>{const {controller:c,store}=ui();storage.saveGame(engine.newGame('Unsynced'),store,storage.SAVE_KEY+'-account-a');store.setItem(storage.SAVE_KEY+'-account-a-cloud-meta',JSON.stringify({pending:true,revision:1}));c.attach(fakeCloud(engine.newGame('Remote newer'),2));await c.loadAccount();assert.equal(c.blocked,true);assert.equal(c.state.name,'Unsynced');await c.loadAccount(true);assert.equal(c.blocked,false);assert.equal(c.state.name,'Remote newer');});
test('Logging out saves account and restores the separate guest world',async()=>{const {controller:c,store}=ui();storage.saveGame(engine.newGame('Guest'),store);const cloud=fakeCloud(engine.newGame('Account'),1);c.attach(cloud);await c.loadAccount();await c.logoutAccount();assert.equal(c.state.name,'Guest');assert.equal(cloud.user,null);assert.equal(storage.loadGame(store).state.name,'Guest');assert.equal(storage.loadGame(store,storage.SAVE_KEY+'-account-a').state.name,'Account');});

test('Ranking escapes commander names and clears cached rows on logout',async()=>{const {controller:c}=ui();const cloud=fakeCloud(engine.newGame('A'),1);cloud.leaderboard=async()=>[{commander:'<img src=x onerror=alert(1)>',rank:1,points:12,building_points:9,research_points:3,fleet_points:0,colonies:0,is_me:true}];c.attach(cloud);await c.loadAccount();await c.refreshRanking(true);assert.ok(c.leaderboard().includes('&lt;img'));assert.ok(!c.leaderboard().includes('<img'));assert.ok(c.leaderboard().includes('· Du'));await c.logoutAccount();const other=fakeCloud(engine.newGame('Other'),1);c.attach(other);assert.ok(!c.leaderboard().includes('&lt;img'));});
test('Late ranking response cannot carry data across account changes',async()=>{const {controller:c}=ui();const cloud=fakeCloud(engine.newGame('A'),1);let resolve;cloud.leaderboard=()=>new Promise(r=>resolve=r);c.attach(cloud);await c.loadAccount();const pending=c.refreshRanking(true);c.clearRanking();c.attach(fakeCloud(engine.newGame('Other'),1));resolve([{commander:'Old Account',rank:1,points:10,building_points:10,research_points:0,fleet_points:0,colonies:0,is_me:true}]);await pending;assert.ok(!c.leaderboard().includes('Old Account'));});
function galaxyReply(){return {start:{x:40,y:500},systems:galaxy.GALAXY_SYSTEMS.map(s=>({...s,planetCount:3})),planets:[{id:'g-helion-p1',system:'helion',slot:1,surveyed:false}],missions:[],serverNow:Date.now()};}
test('Galaxy controller preserves unknown targets, applies authoritative changes and clears data across accounts',async()=>{const {controller:c}=ui(),s=engine.newGame('Galaxie');s.galaxy={x:40,y:500};s.planets[0].ships.longProbe=1;const cloud=fakeCloud(s,1);cloud.galaxyView=async()=>galaxyReply();cloud.galaxySync=async action=>{assert.equal(action.kind,'scan');const next=structuredClone(c.state);next.planets[0].ships.longProbe=0;cloud.revision++;return {state:next,galaxy:{...galaxyReply(),missions:[{id:'m',kind:'scan',from:'home',to:'g-helion-p1',system:'helion',slot:1,start:Date.now(),arrival:Date.now()+10000,due:Date.now()+20000}]}};};c.attach(cloud);await c.loadAccount();await c.refreshGalaxy(true);assert.equal(c.galaxyData.planets[0].surveyed,false);c.showGalaxy();const markup=c.galaxy(c.state.planets[0]);assert.ok(markup.includes('P1 · Unbekannt'));assert.ok(!markup.includes('×undefined'));await c.launchGalaxy('scan','g-helion-p1');assert.equal(c.state.planets[0].ships.longProbe,0);assert.equal(c.galaxyData.missions.length,1);assert.equal(c.galaxyBusy,false);c.clearRanking();assert.equal(c.galaxyData,null);});
test('Late galaxy reply cannot expose surveys from a previous account; errors release the UI lock',async()=>{const {controller:c}=ui(),s=engine.newGame('A');s.galaxy={x:40,y:500};const cloud=fakeCloud(s,1);let resolve;cloud.galaxyView=()=>new Promise(r=>resolve=r);c.attach(cloud);await c.loadAccount();const pending=c.refreshGalaxy(true);c.clearRanking();c.attach(fakeCloud(engine.newGame('B'),1));resolve({...galaxyReply(),planets:[{id:'g-helion-p1',system:'helion',slot:1,surveyed:true,name:'Secret'}]});await pending;assert.equal(c.galaxyData,null);assert.equal(c.galaxyBusy,false);const other=fakeCloud(s,1);other.galaxyView=async()=>{throw Error('network down');};c.attach(other);await c.refreshGalaxy(true);assert.equal(c.galaxyBusy,false);assert.equal(c.galaxyData,null);});

test('First login without a cloud save opens home-world setup and blocks autosave',async()=>{const {controller:c}=ui();c.attach(fakeCloud(null,0));await c.loadAccount();assert.equal(c.blocked,true);assert.ok(c.dialog.innerHTML.includes('Deine Heimatwelt erstellen'));assert.ok(c.dialog.innerHTML.includes('Heimatwelt erstellen'));assert.equal(await c.flushCloud(),false);});

test('Trade overview separates active routes from creation and escapes names with real mixed fleet data',async()=>{const {controller:c}=ui();let s=engine.newGame('Routes');s.planets.push({...structuredClone(s.planets[0]),...config.TARGETS[0]});s.planets[0].ships.transport=2;s.planets[0].ships.karawane=1;const z=()=>config.vector([0,0,0]);s=engine.act(s,{type:'route',fleet:{transport:2,karawane:1},name:'<Metall>',stops:[{planet:'home',load:z(),unload:z()},{planet:'ferrum',load:z(),unload:z()}],repeat:true},s.time);c.attach(fakeCloud(s,1));await c.loadAccount();let html=c.tradeRoutes(c.state.planets[0]);assert.ok(html.includes('Bestehende Routen'));assert.ok(!html.includes('id="route-form"'));assert.ok(html.includes('&lt;Metall&gt;'));assert.ok(!html.includes('<Metall>'));assert.ok(html.includes('2 × Kleiner Transporter'));assert.ok(html.includes('1 × Karawane'));assert.ok(html.includes('role="progressbar"'));c.setRouteFilter('does not exist','all');html=c.tradeRoutes(c.state.planets[0]);assert.ok(/data-route-card="1" hidden/.test(html));c.setRouteView('new');html=c.tradeRoutes(c.state.planets[0]);assert.ok(html.includes('id="route-form"'));assert.ok(!html.includes('data-route-card='));});
test('Editing a route opens only its editor and saving returns to the overview with pending changes',async()=>{const {controller:c}=ui();let s=engine.newGame('Routes');s.planets.push({...structuredClone(s.planets[0]),...config.TARGETS[0]});s.planets[0].ships.transport=2;const stops=[{planet:'home',load:config.vector([0,0,0]),unload:config.vector([0,0,0])},{planet:'ferrum',load:config.vector([0,0,0]),unload:config.vector([0,0,0])}];s=engine.act(s,{type:'route',fleet:{transport:1},name:'Versorgung',stops,repeat:true},s.time);c.attach(fakeCloud(s,1));await c.loadAccount();const id=c.state.missions[0].id;c.setRouteView('existing',id);let html=c.tradeRoutes(c.state.planets[0]);assert.ok(html.includes(`data-route-id="${id}"`));assert.ok(!html.includes('data-route-card='));c.command({type:'edit-route',id,fleet:{transport:2},name:'Neue Versorgung',stops,repeat:true});assert.equal(c.routeSection,'existing');html=c.tradeRoutes(c.state.planets[0]);assert.ok(!html.includes('id="route-form"'));assert.ok(html.includes('Änderung vorgemerkt'));assert.equal(c.state.missions[0].name,'Versorgung');assert.equal(c.state.missions[0].pending.name,'Neue Versorgung');});

test('Galaxy shows foreign colonies and reservations without scanning, escapes commanders, and keeps yield details hidden',async()=>{const {controller:c}=ui(),s=engine.newGame('A');const cloud=fakeCloud(s,1);let reserved=true;cloud.galaxyView=async()=>({...galaxyReply(),planets:[{...galaxyReply().planets[0],owner:'foreign',reserved,commander:'<Silverstar>'}]});c.attach(cloud);await c.loadAccount();await c.refreshGalaxy(true);c.showGalaxy();let html=c.galaxy(c.state.planets[0]);assert.ok(html.includes('Reserviert durch &lt;Silverstar&gt;'));assert.ok(html.includes('0 besiedelt · 1 reserviert'));assert.ok(!html.includes('durch <Silverstar>'));assert.ok(html.includes('class="orbit-commander">&lt;Silverstar&gt;</strong>'));assert.ok(html.includes('P1 · reserviert'));assert.ok(html.includes('orbit-foreign orbit-reserved'));assert.ok(!html.includes('class="yields"'));assert.ok(!html.includes('Interstellar kolonisieren'));reserved=false;await c.refreshGalaxy(true);html=c.galaxy(c.state.planets[0]);assert.ok(html.includes('Besiedelt durch &lt;Silverstar&gt;'));assert.ok(html.includes('1 besiedelt'));assert.ok(html.includes('Nicht untersucht'));assert.ok(!html.includes('class="yields"'));});

test('Construction and research use complete generated art, while all planet views share stable variants',async()=>{const {controller:c}=ui();c.attach(fakeCloud(engine.newGame('Assets'),1));await c.loadAccount();const p=c.state.planets[0];const b=c.buildings(p),r=c.research(p);for(const key of Object.keys(config.BUILDINGS))assert.ok(b.includes(config.BUILDINGS[key].asset||`buildings/${key}.webp`));for(const key of Object.keys(config.TECHS))assert.ok(r.includes(config.TECHS[key].asset||`research/${key}.webp`));assert.ok(!b.includes('⛏'));assert.ok(!r.includes('⚗'));assert.ok(c.orb(p).includes('./assets/home.webp'));const q={...p,id:'g-helion-p2',image:'ferrum'};assert.ok(c.orb(q).includes(config.planetImagePath(q)));});

test('Ship cancellation shows the selected order and waits for server capability',async()=>{
 const {controller:c}=ui();let s=engine.newGame('Shipyard');s.tech.scout=1;s.tech.logistics=1;s.planets[0].buildings.shipyard=1;s=engine.act(s,{type:'ship',key:'transport',count:1},s.time);
 const cloud=fakeCloud(s,1);cloud.authoritative=true;cloud.now=s.time;cloud.pvp={features:{cancelShip:true}};c.attach(cloud);await c.loadAccount();let html=c.shipJobPanel(c.state.planets[0]);assert.ok(html.includes('data-action="cancel-ship"'));assert.ok(html.includes('data-order-id="'+s.planets[0].shipjob.id+'"'));assert.ok(!html.includes('Serverfunktion aktualisiert'));
 cloud.pvp.features={};html=c.shipJobPanel(c.state.planets[0]);assert.ok(html.includes('Serverfunktion aktualisiert'));assert.match(html,/data-action="cancel-ship"[^>]*disabled/);
});

test('Report reads isolate accounts and reject a late response after logout',async()=>{const {controller:c}=ui();const cloud=fakeCloud(engine.newGame('A'),1);let resolve;cloud.reports=()=>new Promise(r=>resolve=r);c.attach(cloud);await c.loadAccount();const pending=c.refreshReports();c.clearRanking();c.attach(fakeCloud(engine.newGame('B'),1));resolve({items:[{id:'private-a',title:'Secret',time:1}],total:1});await pending;assert.equal(c.reportData.items.length,0);});
test('A newer report request wins when earlier filters return late',async()=>{const {controller:c}=ui();const cloud=fakeCloud(engine.newGame('A'),1),replies=[];cloud.reports=()=>new Promise(r=>replies.push(r));c.attach(cloud);await c.loadAccount();const old=c.refreshReports(),fresh=c.refreshReports();replies[1]({items:[{id:'new',time:2}],total:1});await fresh;replies[0]({items:[{id:'old',time:1}],total:1});await old;assert.equal(c.reportData.items[0].id,'new');});
test('Report accordions capture current DOM state before periodic rendering',()=>{const {controller:c,doc}=ui();doc.querySelectorAll=()=>[{dataset:{reportId:'battle'},open:true},{dataset:{uiKey:'mission:one'},open:true}];c.captureReportUI();assert.equal(c.reportOpened.has('battle'),true);assert.equal(c.reportOpened.has('mission:one'),true);doc.querySelectorAll=()=>[{dataset:{reportId:'battle'},open:false}];c.captureReportUI();assert.equal(c.reportOpened.has('battle'),false);assert.equal(c.reportOpened.has('mission:one'),true);});

// Exercise submit bubbling through both app and document listeners, as in the browser.
for(const [id,op,fields] of [
 ['social-invite-form','invite',{friend:'b',delivery:'on',defense:'on'}],
 ['social-flight-form','deliver',{to:'g-orion-p1','fleet-karawane':'2','cargo-metal':'100'}],
 ['social-flight-form','support',{to:'g-orion-p1','fleet-waechter':'3'}],
 ['social-flight-form','trade-offer',{to:'g-orion-p1','fleet-karawane':'1','cargo-metal':'100','payment-crystal':'50'}],
 ['rights-form','permissions',{delivery:'on'}]
])test(`Partner ${op} submission sends exactly one social request during event bubbling`,async()=>{
 class FormDataMock{constructor(form){this.fields=form.fields;}get(key){return this.fields[key]??null;}has(key){return Object.hasOwn(this.fields,key);}}
 const {controller:c,submit}=ui(FormDataMock),cloud=fakeCloud(engine.newGame('Partner'),1),requests=[];c.attach(cloud);await c.loadAccount();cloud.authoritative=true;
 cloud.gameRequest=async request=>{requests.push(request);return {state:structuredClone(c.state)};};
 await submit({id,dataset:{op,id:'partner-id'},fields,classList:{contains:cls=>id==='rights-form'&&cls==='social-rights-form'}});
 assert.equal(requests.length,1);assert.equal(requests[0].type,'social');assert.equal(requests[0].action.op,op);
 if(op==='invite')assert.deepEqual(requests[0].action,{op,friend:'b',delivery:true,defense:true});
 if(op==='deliver')assert.deepEqual(requests[0].action.fleet,{karawane:2});
 if(op==='support')assert.deepEqual(requests[0].action.fleet,{waechter:3});
 if(op==='trade-offer')assert.equal(requests[0].action.payment.crystal,50);
 if(op==='permissions')assert.deepEqual(requests[0].action,{op,id:'partner-id',delivery:true,defense:false});
 assert.equal(c.galaxyBusy,false);
});
