import test from 'node:test';
import assert from 'node:assert/strict';
import {newGame,act,advance,researchInfo,shipInfo,legInfo,routeLegInfo,routeInfo} from '../src/engine.js';
import {TECHS,SHIPS,TARGETS,RES,vector} from '../src/config.js';
import {validateSave} from '../src/storage.js';
function ready(){const s=newGame('Triebwerkstest',1800000000000),p=s.planets[0];p.buildings.lab=5;p.buildings.warehouse=15;p.buildings.shipyard=6;p.resources=vector([100000,100000,100000]);for(const k of RES)p.buildings[k]=0;for(const [k,t] of Object.entries(TECHS))s.tech[k]=t.max;return s;}
const step=s=>advance(s,Math.min(...s.missions.map(m=>m.due)));
test('Three tutorial colonies persist with a fourth total planet and no advanced engine',()=>{let s=ready();s.tech.colonization=3;s.tech.ramjet=0;s.tech.impulse=0;s.tech.hyperspace=0;s.discovered=TARGETS.map(t=>t.id);s.planets[0].ships.colony=3;for(const t of TARGETS)s=act(s,{type:'colony',to:t.id},s.time);assert.equal(s.missions.length,3);while(s.missions.length)s=step(s);s=validateSave(s);assert.equal(s.planets.length,4);assert.equal(s.planets[0].ships.colony,0);assert.deepEqual(new Set(s.planets.map(p=>p.id)),new Set(['home',...TARGETS.map(t=>t.id)]));});
test('Reserved colony missions cannot exceed research and increasing tutorial research opens third slot',()=>{let s=ready();s.tech.colonization=2;s.discovered=TARGETS.map(t=>t.id);s.planets[0].ships.colony=3;s=act(s,{type:'colony',to:TARGETS[0].id},s.time);s=act(s,{type:'colony',to:TARGETS[1].id},s.time);const before=JSON.stringify(s);assert.throws(()=>act(s,{type:'colony',to:TARGETS[2].id},s.time),/Kolonisierungsstufe/);assert.equal(JSON.stringify(s),before);s.tech.colonization=3;assert.equal(act(s,{type:'colony',to:TARGETS[2].id},s.time).missions.length,3);});
test('Engine and extra colony progression gates each research stage',()=>{const s=ready(),p=s.planets[0];for(const [key,prev] of [['ramjet','drive'],['impulse','ramjet'],['hyperspace','impulse']]){s.tech[key]=0;s.tech[prev]=2;assert.match(researchInfo(s,p,key).reason,/Stufe 3/);s.tech[prev]=3;assert.equal(researchInfo(s,p,key).reason,'');}for(const [i,key] of ['ramjet','impulse','hyperspace'].entries()){s.tech.colonization=3+i;s.tech[key]=0;assert.match(researchInfo(s,p,'colonization').reason,new RegExp(TECHS[key].name));s.tech[key]=1;assert.equal(researchInfo(s,p,'colonization').reason,'');}s.tech.colonization=6;assert.match(researchInfo(s,p,'colonization').reason,/Maximale/);});
test('Advanced ship building uses the assigned engine and only that engine improves flights',()=>{for(const ship of ['karawane','waechter','atlas','donner','arche','titan']){const s=ready(),p=s.planets[0],def=SHIPS[ship],to=TARGETS[2];s.tech[def.engine]=0;assert.match(shipInfo(s,p,ship).reason,new RegExp(TECHS[def.engine].name));s.tech[def.engine]=def.engineLevel;assert.equal(shipInfo(s,p,ship).reason,'');const before=legInfo(s,p,to,10,ship);s.tech.drive=0;assert.deepEqual(legInfo(s,p,to,10,ship),before);for(const engine of ['ramjet','impulse','hyperspace'])if(engine!==def.engine)s.tech[engine]=0;assert.deepEqual(legInfo(s,p,to,10,ship),before);s.tech[def.engine]=5;const after=legInfo(s,p,to,10,ship);assert.ok(after.ms<before.ms);assert.ok(after.fuel<before.fuel);}});
test('Saving older worlds adds new engine counters without replacing existing drive level or flights',()=>{let s=ready();s.planets[0].ships.probe=1;s=act(s,{type:'probe',to:'ferrum'},s.time);const old=structuredClone(s.missions[0]);for(const key of ['ramjet','impulse','hyperspace'])delete s.tech[key];s=validateSave(s);assert.equal(s.tech.drive,5);for(const key of ['ramjet','impulse','hyperspace'])assert.equal(s.tech[key],0);assert.deepEqual(s.missions[0],old);s.tech.ramjet=null;assert.throws(()=>validateSave(s));});
test('Trade economy applies to real first and later legs, charged full cycle matches estimate',()=>{let s=ready(),p=s.planets[0];const q=structuredClone(p);Object.assign(q,TARGETS[0]);s.planets.push(q);p.ships.karawane=10;const stops=['home','ferrum'].map(planet=>({planet,load:vector([0,0,0]),unload:vector([0,0,0])}));const direct=legInfo(s,p,q,10,'karawane'),economy=routeLegInfo(s,p,q,10,'karawane');assert.equal(economy.ms,Math.ceil(direct.ms*1.25));assert.equal(economy.fuel,Math.ceil(direct.fuel*.75));assert.ok(economy.fuel<direct.fuel);const round=routeInfo(s,stops,10,'karawane'),fuel=p.resources.fuel;s=act(s,{type:'route',ship:'karawane',count:10,stops,repeat:true},s.time);assert.equal(s.planets[0].resources.fuel,fuel-round.fuel);assert.equal(s.missions[0].duration,economy.ms);s=step(s);assert.equal(s.missions[0].duration,economy.ms);s=step(s);assert.equal(s.planets[0].resources.fuel,fuel-2*round.fuel);assert.equal(s.missions[0].duration,economy.ms);});
