import test from 'node:test';
import assert from 'node:assert/strict';
import {newGame,act,advance,stats,capacity,cargoCapacity} from '../src/engine.js';
import {RES,vector} from '../src/config.js';
import {validateSave,parseSave,loadGame,saveGame,SAVE_KEY} from '../src/storage.js';
const NOW=1800000000000;
function prepared(){const s=newGame('Test',NOW),p=s.planets[0];p.buildings.lab=2;p.buildings.shipyard=1;s.tech.scout=1;s.tech.logistics=1;s.tech.colonization=1;p.ships.probe=1;p.ships.colony=1;p.ships.transport=2;return s;}
function complete(s){const end=Math.max(s.time,s.research?.end||0,...s.planets.map(p=>Math.max(p.build?.end||0,p.shipjob?.end||0)),...s.missions.map(m=>m.due));return advance(s,end);}
function discoveredColony(){let s=prepared();s=act(s,{type:'probe',to:'ferrum'},s.time);s=complete(s);s=complete(s);s=act(s,{type:'colony',to:'ferrum'},s.time);return complete(s);}
function totals(s){return Object.fromEntries(RES.map(k=>[k,s.planets.reduce((n,p)=>n+p.resources[k]+p.depot[k],0)+s.missions.reduce((n,m)=>n+m.cargo[k],0)]));}
test('Eight hours equal hourly progression, including a mine upgrade halfway',()=>{let s=newGame('Test',NOW);s=act(s,{type:'build',key:'metal'},NOW);s.planets[0].build.end=NOW+4*3600000;const a=advance(structuredClone(s),NOW+8*3600000),b=structuredClone(s);for(let h=1;h<=8;h++)advance(b,NOW+h*3600000);for(const k of RES)assert.ok(Math.abs(a.planets[0].resources[k]-b.planets[0].resources[k])<1e-7);assert.equal(a.planets[0].buildings.metal,2);assert.equal(a.reports.length,1);});
test('Mine production changes only at its actual completion time',()=>{let s=newGame('Test',NOW);s.planets[0].resources=vector([200,200,100]);s=act(s,{type:'build',key:'metal'},NOW);s.planets[0].build.end=NOW+3600000;const before=s.planets[0].resources.metal,old=stats(s,s.planets[0]).rates.metal;const mid=advance(structuredClone(s),NOW+3600000),rate=stats(mid,mid.planets[0]).rates.metal;advance(s,NOW+2*3600000);assert.ok(Math.abs(s.planets[0].resources.metal-(before+old+rate))<1e-7);});
test('Energy shortage slows production and warehouse caps it',()=>{const s=newGame('Test',NOW),p=s.planets[0];p.buildings.solar=0;assert.equal(stats(s,p).rates.metal,0);const metal=p.resources.metal;advance(s,NOW+3600000);assert.equal(p.resources.metal,metal);p.buildings.solar=10;advance(s,NOW+100*3600000);assert.equal(p.resources.metal,capacity(p));});
test('Locked actions fail atomically',()=>{const s=newGame('Test',NOW),before=JSON.stringify(s);assert.throws(()=>act(s,{type:'research',key:'colonization'},NOW),/Forschungslabor/);assert.throws(()=>act(s,{type:'build',key:'tidal'},NOW),/Energietechnik/);assert.equal(JSON.stringify(s),before);});
test('Probe reports arrive, ship returns, colony consumes its ship and starts locally',()=>{let s=prepared();s=act(s,{type:'probe',to:'ferrum'},s.time);assert.equal(s.planets[0].ships.probe,0);s=complete(s);assert.deepEqual(s.discovered,['ferrum']);assert.equal(s.planets[0].ships.probe,0);s=complete(s);assert.equal(s.planets[0].ships.probe,1);s=act(s,{type:'colony',to:'ferrum'},s.time);assert.throws(()=>act(s,{type:'colony',to:'nereus'},s.time));s=complete(s);assert.equal(s.planets.length,2);assert.equal(s.planets[1].resources.metal,350);assert.equal(s.planets[0].ships.colony,0);assert.equal(s.missions.length,0);assert.equal(s.planets[1].buildings.solar,2);});
test('Transport conserves cargo, charges fuel, reserves and returns ships',()=>{let s=discoveredColony();for(const p of s.planets){for(const k of RES)p.buildings[k]=0;}s.planets[1].ships.transport=1;const old=totals(s),cargo=vector([200,100,20]);s=act(s,{type:'transport',planet:'ferrum',to:'home',count:1,cargo},s.time+1);assert.throws(()=>act(s,{type:'transport',planet:'ferrum',to:'home',count:1,cargo},s.time),/Schiffe/);const after=totals(s);assert.equal(after.metal,old.metal);assert.equal(after.crystal,old.crystal);assert.ok(after.fuel<old.fuel);s=complete(s);assert.deepEqual(totals(s),after);s=complete(s);assert.equal(s.planets[1].ships.transport,1);assert.deepEqual(totals(s),after);advance(s,s.time+10000);assert.equal(s.planets[1].ships.transport,1);});
test('Incoming overflow is retained in depot and fills freed storage',()=>{let s=discoveredColony();for(const p of s.planets){for(const k of RES)p.buildings[k]=0;}const dest=s.planets[1];dest.resources.metal=capacity(dest)-50;const before=totals(s);s=act(s,{type:'transport',planet:'home',to:'ferrum',count:1,cargo:vector([200,0,0])},s.time);s=complete(s);assert.equal(s.planets[1].resources.metal,capacity(s.planets[1]));assert.equal(s.planets[1].depot.metal,150);assert.equal(totals(s).metal,before.metal);s=act(s,{type:'build',planet:'ferrum',key:'metal'},s.time);assert.equal(s.planets[1].resources.metal,capacity(s.planets[1]));assert.equal(s.planets[1].depot.metal,70);});
test('First colony and first transport are reachable from the unmodified starting economy',()=>{let s=newGame('Sebastian',NOW);const go=a=>{s=act(s,a,s.time);s=complete(s);};go({type:'build',key:'lab'});go({type:'research',key:'scout'});go({type:'build',key:'shipyard'});go({type:'ship',key:'probe',count:1});go({type:'probe',to:'ferrum'});s=complete(s);go({type:'build',key:'lab'});go({type:'research',key:'colonization'});go({type:'ship',key:'colony',count:1});go({type:'colony',to:'ferrum'});go({type:'research',key:'logistics'});go({type:'ship',key:'transport',count:1});go({type:'transport',to:'ferrum',count:1,cargo:vector([500,350,50])});s=complete(s);go({type:'build',planet:'ferrum',key:'metal'});go({type:'build',planet:'ferrum',key:'lab'});go({type:'build',planet:'ferrum',key:'shipyard'});go({type:'ship',planet:'ferrum',key:'transport',count:1});go({type:'transport',planet:'ferrum',to:'home',count:1,cargo:vector([100,0,0])});assert.equal(s.planets.length,2);assert.ok(s.reports.some(r=>r.title==='Transport angekommen'));validateSave(s);});
test('Transport capacity is enforced before spending anything',()=>{let s=discoveredColony();const before=JSON.stringify(s);assert.throws(()=>act(s,{type:'transport',planet:'home',to:'ferrum',count:1,cargo:vector([cargoCapacity(s)+1,0,0])},s.time),/Laderaum/);assert.equal(JSON.stringify(s),before);assert.throws(()=>act(s,{type:'transport',planet:'home',to:'ferrum',count:1,cargo:vector([-1,0,0])},s.time));});
test('Storage roundtrip preserves missions and no event resolves twice',()=>{let s=prepared();s=act(s,{type:'probe',to:'nereus'},s.time);s=parseSave(JSON.stringify(s));s=complete(s);const seq=s.seq;s=parseSave(JSON.stringify(s));advance(s,s.time);assert.equal(s.seq,seq);s=complete(s);const ships=s.planets[0].ships.probe;advance(s,s.time+100000);assert.equal(s.planets[0].ships.probe,ships);});
test('Import rejects malformed data, nonfinite values, fake targets and excessive payloads',()=>{const s=prepared();validateSave(s);const bad=structuredClone(s);bad.planets[0].resources.metal=-1;assert.throws(()=>validateSave(bad));assert.throws(()=>parseSave('{bad'));assert.throws(()=>parseSave('x'.repeat(2000001)));const b=structuredClone(s);b.tech.drive=999;assert.throws(()=>validateSave(b));const c=structuredClone(s);c.planets[0].color='red;background:url(x)';assert.throws(()=>validateSave(c));});
test('Last intact backup can recover a damaged latest save',()=>{const memory=new Map(),store={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)};const s=prepared();saveGame(s,store);saveGame(s,store);store.setItem(SAVE_KEY,'broken');const recovered=loadGame(store);assert.equal(recovered.recovered,true);assert.equal(recovered.state.name,'Test');});
test('Research and shipbuilding progress while a planet is building',()=>{let s=prepared();s=act(s,{type:'build',key:'metal'},s.time);s=act(s,{type:'research',key:'drive'},s.time);s=act(s,{type:'ship',key:'transport',count:1},s.time);s=complete(s);assert.equal(s.planets[0].buildings.metal,2);assert.equal(s.tech.drive,1);assert.equal(s.planets[0].ships.transport,3);});
