import test from 'node:test';import assert from 'node:assert/strict';
import {GALAXY_SYSTEMS,galaxyDistance,galaxyFlight,validateGalaxy} from '../src/galaxy.js';
import {newGame,act,advance,routeInfo,legInfo} from '../src/engine.js';
import {TECHS,TARGETS,vector} from '../src/config.js';
import {validateSave} from '../src/storage.js';import {createCloud,CloudConflict} from '../src/cloud.js';
const data=()=>({start:{x:50,y:500},systems:GALAXY_SYSTEMS.map(s=>({...s,planetCount:3})),planets:[{id:'g-helion-p1',system:'helion',slot:1,surveyed:false}],missions:[],serverNow:Date.now()});
test('Public galaxy catalogue has ten systems and distance drives both real time and fuel estimates',()=>{assert.equal(GALAXY_SYSTEMS.length,10);const s=newGame(),start={x:50,y:500};s.tech.ramjet=1;const near=galaxyFlight(s,s.planets[0],{x:60,y:500},start),far=galaxyFlight(s,s.planets[0],{x:900,y:500},start);assert.ok(far.ms>near.ms);assert.ok(far.fuel>near.fuel);s.tech.ramjet=5;assert.ok(galaxyFlight(s,s.planets[0],{x:900,y:500},start).ms<far.ms);assert.equal(galaxyDistance(start,{x:50,y:500}),1);});
test('Unknown planet response rejects private fields even if a malicious endpoint sends them',()=>{for(const field of ['name','kind','mult','owner','energy','ocean','image']){const d=data();d.planets[0][field]='secret';assert.throws(()=>validateGalaxy(d),/freigegebene/);}assert.equal(validateGalaxy(data()).systems.length,10);const bad=data();bad.systems[0].planetCount=11;assert.throws(()=>validateGalaxy(bad));});
function colony(s,slot=1){return {...structuredClone(s.planets[0]),id:'g-helion-p'+slot,name:'Helion '+slot,system:'helion',slot,x:520,y:400,image:'ferrum',distance:slot};}
test('Seven planets survive saves; advanced freighters connect tutorial to shared colonies, early ships remain local',()=>{let s=newGame('Galaxie',1800000000000);s.galaxy={x:50,y:500};for(const [k,t] of Object.entries(TECHS))s.tech[k]=t.max;for(const t of TARGETS)s.planets.push({...structuredClone(s.planets[0]),...t});for(let i=1;i<=3;i++)s.planets.push(colony(s,i));s=validateSave(s);assert.equal(s.planets.length,7);const p=s.planets[0];p.buildings.warehouse=15;p.resources=vector([10000,10000,10000]);p.ships.transport=1;p.ships.karawane=2;assert.throws(()=>act(s,{type:'station',ship:'transport',count:1,to:'g-helion-p1'},s.time),/Interstellare/);assert.throws(()=>act(s,{type:'transport',count:1,to:'g-helion-p1',cargo:vector([100,0,0])},s.time),/Interstellare/);const stops=['home','g-helion-p1'].map(planet=>({planet,load:vector([0,0,0]),unload:vector([0,0,0])}));assert.throws(()=>routeInfo(s,stops,1,'transport'),/Interstellare/);const old=p.resources.fuel,f=legInfo(s,p,s.planets[4],1,'karawane');s=act(s,{type:'station',ship:'karawane',count:1,to:'g-helion-p1',order:vector([100,0,0])},s.time);s=advance(s,s.missions[0].due);assert.equal(s.planets[4].ships.karawane,1);assert.ok(s.planets[0].resources.fuel>=old-f.fuel);validateSave(s);});
test('Cloud galaxy operations require login/load, use revision lease, validate response and recover conflict',async()=>{let revision=1,mode='ok',calls=[];const s=newGame();const client={auth:{getSession:async()=>({data:{session:{user:{id:'a'}}}})},from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:{state:s,revision:1}})})})}),rpc:async(name,args)=>{calls.push({name,args});if(mode==='missing')return {error:{code:'PGRST202'}};if(name==='imperium_galaxy_view')return {data:data()};if(mode==='conflict')return {error:{message:'SAVE_CONFLICT'}};return {data:{state:s,revision:++revision,galaxy:data()}};}};const c=createCloud(client);await assert.rejects(c.galaxyView(),/anmelden/);await c.session();await assert.rejects(c.galaxySync(),/zuerst laden/);await c.load();assert.equal((await c.galaxyView()).systems.length,10);const result=await c.galaxySync({kind:'scan',from:'home',to:'g-helion-p1'});assert.equal(c.revision,2);assert.equal(result.state.version,1);assert.deepEqual(calls.at(-1).args,{p_expected:1,p_kind:'scan',p_from:'home',p_to:'g-helion-p1'});mode='conflict';await assert.rejects(c.galaxySync(),CloudConflict);assert.equal(c.loaded,false);await c.load();mode='missing';await assert.rejects(c.galaxyView(),/galaxy.sql/);assert.equal(c.loaded,true);});
