import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {newGame} from '../src/engine.js';
import {TECHS,vector} from '../src/config.js';
import {validateSave} from '../src/storage.js';
import {validateGalaxy} from '../src/galaxy.js';
const A='00000000-0000-0000-0000-000000000001',B='00000000-0000-0000-0000-000000000002';
test('Postgres galaxy migration: secrecy, atomic missions, ownership and revision safeguards',async t=>{
 const db=new PGlite();t.after(()=>db.close());
 await db.exec("create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create role anon;create role authenticated;");
 for(const f of ['setup.sql','leaderboard.sql','ship-tiers.sql','galaxy.sql'])await db.exec(readFileSync('supabase/'+f,'utf8'));
 const uid=async id=>db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);
 const view=async()=>validateGalaxy((await db.query('select public.imperium_galaxy_view() as data')).rows[0].data);
 const sync=async(revision,kind=null,from=null,to=null)=>(await db.query('select public.imperium_galaxy_sync($1,$2,$3,$4) as data',[revision,kind,from,to])).rows[0].data;
 const save=async(s,revision)=>(await db.query('select public.save_imperium($1::jsonb,$2) as revision',[JSON.stringify(s),revision])).rows[0].revision;
 for(const id of [A,B]){await db.query('insert into auth.users values($1)',[id]);await uid(id);const s=newGame(id);for(const [k,tech] of Object.entries(TECHS))s.tech[k]=tech.max;s.planets[0].ships.longProbe=3;s.planets[0].ships.starColony=3;await save(s,0);}
 await uid(A);let a,initial=await view(),target=initial.planets[0].id;
 await t.test('Ten shared systems, 3–10 permanent planets, stable private edge start, no hidden payload fields',async()=>{assert.equal(initial.systems.length,10);assert.ok(initial.systems.every(s=>s.planetCount>=3&&s.planetCount<=10));assert.ok(initial.planets.every(p=>!p.surveyed&&Object.keys(p).length===4));assert.ok(Math.abs(Math.hypot(initial.start.x-500,initial.start.y-500)-460)<.02);const before=(await db.query('select id,meta from public.galaxy_planets order by id')).rows;await db.exec(readFileSync('supabase/galaxy.sql','utf8'));assert.deepEqual((await db.query('select id,meta from public.galaxy_planets order by id')).rows,before);assert.deepEqual((await view()).start,initial.start);});
 await t.test('Raw tables and internal cross-user projection are inaccessible to logged-in clients',async()=>{await db.exec('set role authenticated');await assert.rejects(db.query('select * from public.galaxy_planets'),/permission denied/);await assert.rejects(db.query('select public.imperium_galaxy_projection($1)',[B]),/permission denied/);assert.equal((await view()).systems.length,10);await db.exec('reset role');await db.exec('set role anon');await assert.rejects(db.query('select public.imperium_galaxy_view()'),/permission denied/);await db.exec('reset role');});
 await t.test('Probe is deducted with flight fuel exactly once; stale revisions and duplicate scan roll back',async()=>{a=await sync(1,'scan','home',target);validateSave(a.state);assert.equal(a.state.planets[0].ships.longProbe,2);assert.ok(a.state.planets[0].resources.fuel<1000);await assert.rejects(sync(1,'scan','home',target),/SAVE_CONFLICT/);await assert.rejects(sync(a.revision,'scan','home',target),/SCAN_UNDERWAY/);const row=(await db.query('select state,revision from public.game_saves where user_id=$1',[A])).rows[0];assert.deepEqual(row.state,a.state);assert.equal(row.revision,a.revision);});
 await t.test('Outward arrival reveals only this player; ship remains bound until the return arrives',async()=>{assert.equal((await view()).planets.find(p=>p.id===target).surveyed,false);await db.query("update public.galaxy_missions set started_at=now()-interval '1 hour',arrival_at=now()-interval '1 second' where user_id=$1",[A]);assert.equal((await view()).planets.find(p=>p.id===target).surveyed,true);await uid(B);assert.equal((await view()).planets.find(p=>p.id===target).surveyed,false);await uid(A);assert.equal(a.state.planets[0].ships.longProbe,2);});
 await t.test('Colony reservation is atomic, prevents a rival claim and rejects forged ownership',async()=>{a=await sync(a.revision,'colony','home',target);validateSave(a.state);assert.equal(a.state.planets[0].ships.starColony,2);await uid(B);await db.query('insert into public.galaxy_surveys(user_id,planet_id) values($1,$2)',[B,target]);await assert.rejects(sync(1,'colony','home',target),/PLANET_TAKEN/);const b=(await db.query('select state from public.game_saves where user_id=$1',[B])).rows[0].state;assert.equal(b.planets[0].ships.starColony,3);const fake=structuredClone(b);const meta=(await db.query('select meta from public.galaxy_planets where id=$1',[target])).rows[0].meta;fake.planets.push({...fake.planets[0],...meta});await assert.rejects(save(fake,1),/INVALID_GALAXY_COLONY/);await uid(A);});
 await t.test('Server flights contribute to ranking while ships are away',async()=>{const row=(await db.query('select * from public.imperium_leaderboard() where is_me')).rows[0];const plain=(await db.query('select * from public.imperium_rank_points($1)',[a.state])).rows[0];assert.ok(row.fleet_points>plain.fleet_points);});
 await t.test('Return and colony arrivals complete once, create valid planet and consume only colony ship',async()=>{await db.query("update public.galaxy_missions set started_at=now()-interval '1 hour',arrival_at=now()-interval '2 seconds',finish_at=now()-interval '1 second' where user_id=$1",[A]);a=await sync(a.revision);validateSave(a.state);validateGalaxy(a.galaxy);assert.equal(a.state.planets[0].ships.longProbe,3);assert.equal(a.state.planets[0].ships.starColony,2);assert.equal(a.state.planets.length,2);assert.equal(a.galaxy.missions.length,0);assert.equal(a.galaxy.planets.find(p=>p.id===target).reserved,false);const again=await sync(a.revision);assert.equal(again.revision,a.revision);assert.deepEqual(again.state,a.state);});
 await t.test('Cloud save accepts owned colony, rejects old imports removing it and immutable metadata tampering',async()=>{a.revision=await save(a.state,a.revision);await assert.rejects(save(newGame('reset'),a.revision),/GALAXY_COLONIES_REQUIRED/);const altered=structuredClone(a.state);altered.planets[1].mult=[10,10,10];await assert.rejects(save(altered,a.revision),/INVALID_GALAXY_COLONY/);assert.deepEqual((await db.query('select state from public.game_saves where user_id=$1',[A])).rows[0].state,a.state);});
 await t.test('Research, fuel, surveyed target and outer colony slots are checked before resources change',async()=>{await uid(B);let b=(await db.query('select state,revision from public.game_saves where user_id=$1',[B])).rows[0];const other=initial.planets[1].id;b.state.tech.ramjet=0;b.revision=await save(b.state,b.revision);await assert.rejects(sync(b.revision,'scan','home',other),/RAMJET_REQUIRED/);b.state.tech.ramjet=1;b.state.planets[0].resources.fuel=0;b.revision=await save(b.state,b.revision);await assert.rejects(sync(b.revision,'scan','home',other),/RESOURCES_REQUIRED/);b.state.planets[0].resources.fuel=1000;b.state.tech.colonization=3;b.revision=await save(b.state,b.revision);await assert.rejects(sync(b.revision,'colony','home',other),/SURVEY_REQUIRED/);await db.query('insert into public.galaxy_surveys(user_id,planet_id) values($1,$2)',[B,other]);await assert.rejects(sync(b.revision,'colony','home',other),/COLONY_LIMIT/);b.state.galaxy=(await view()).start;assert.deepEqual((await db.query('select state from public.game_saves where user_id=$1',[B])).rows[0].state,b.state);});
});
