import test from 'node:test';
import assert from 'node:assert/strict';
import {newGame,act,advance,routeInfo,routeLegInfo,fleetCapacity,fleetManifest} from '../src/engine.js';
import {TARGETS,vector} from '../src/config.js';
import {validateSave} from '../src/storage.js';
function fixture(){const s=newGame('Mix');s.planets.push({...structuredClone(s.planets[0]),...TARGETS[0]});for(const p of s.planets){for(const k in p.buildings)p.buildings[k]=0;p.resources=vector([2000,1000,3000]);p.ships.karawane=5;p.ships.atlas=3;p.ships.transport=4;}s.tech.logistics=2;s.tech.ramjet=2;s.tech.impulse=2;return s;}
const orders=(metal=0)=>({metal,crystal:0,fuel:0});
const stops=(metal=400)=>[{planet:'home',load:orders(metal),unload:orders()},{planet:'ferrum',load:orders(),unload:orders('max')}];
const route=(s,fleet={karawane:2,atlas:1},repeat=true)=>act(s,{type:'route',name:'Mixroute',fleet,stops:stops(),repeat},s.time);
function totals(s){const ships={};for(const p of s.planets)for(const [k,n] of Object.entries(p.ships))ships[k]=(ships[k]||0)+n;for(const m of s.missions)for(const [k,n] of Object.entries(fleetManifest(m)))ships[k]=(ships[k]||0)+n;return ships;}
function atHome(s){let m=s.missions[0];while(m.index!==0){advance(s,m.due);m=s.missions[0];}advance(s,m.due);return s;}
test('Mixed route adds researched capacity and per-type fuel; slowest researched ship sets every leg',()=>{const s=fixture(),fleet={karawane:2,atlas:1},info=routeInfo(s,stops(),fleet);assert.equal(info.capacity,fleetCapacity(s,fleet));let ms=0,fuel=0;for(const [a,b] of [[s.planets[0],s.planets[1]],[s.planets[1],s.planets[0]]]){const k=routeLegInfo(s,a,b,2,'karawane'),t=routeLegInfo(s,a,b,1,'atlas');ms+=Math.max(k.ms,t.ms);fuel+=k.fuel+t.fuel;}assert.equal(info.ms,ms);assert.equal(info.fuel,fuel);const r=route(s);assert.deepEqual(totals(r),totals(s));assert.equal(r.planets[0].ships.atlas,2);assert.deepEqual(validateSave(r).missions[0].fleet,fleet);});
test('Queued changes do not alter in-flight cargo/time; arrival atomically swaps, unloads cargo, applies amounts and repeat',()=>{const initial=fixture();let s=route(initial);const before=structuredClone(s.missions[0]);s=act(s,{type:'edit-route',id:before.id,name:'Neu',fleet:{atlas:2},stops:stops(50),repeat:false},s.time);assert.equal(s.missions[0].due,before.due);assert.deepEqual(s.missions[0].cargo,before.cargo);assert.deepEqual(s.missions[0].fleet,before.fleet);s=validateSave(s);atHome(s);assert.equal(s.missions.length,0);assert.deepEqual(totals(s),totals(initial));assert.equal(s.planets[1].resources.metal,2400);assert.equal(s.planets[0].resources.metal,1600);assert.ok(s.reports.some(r=>r.title==='Routenänderung aktiviert'));});
test('Missing replacement ships keep whole old route and pending plan; later arrival retries successfully',()=>{const initial=fixture();let s=route(initial);s=act(s,{type:'edit-route',id:s.missions[0].id,name:'Später',fleet:{atlas:4},stops:stops(0),repeat:true},s.time);atHome(s);assert.equal(s.missions[0].name,'Mixroute');assert.deepEqual(s.missions[0].fleet,{karawane:2,atlas:1});assert.ok(s.missions[0].pending);s.planets[0].ships.atlas+=1;const all=totals(s);atHome(s);assert.equal(s.missions[0].name,'Später');assert.deepEqual(s.missions[0].fleet,{atlas:4});assert.equal(s.missions[0].pending,undefined);assert.deepEqual(totals(s),all);});
test('Same fleet edit needs no extra orbit ships; stop dominates pending switch; invalid edits are atomic',()=>{let s=route(fixture());const all=totals(s);s.planets[0].ships.karawane=0;s.planets[0].ships.atlas=0;const fleet=fleetManifest(s.missions[0]);s=act(s,{type:'edit-route',id:s.missions[0].id,name:'Mengen',fleet,stops:stops(20),repeat:true},s.time);atHome(s);assert.equal(s.missions[0].name,'Mengen');s=act(s,{type:'stop-route',id:s.missions[0].id},s.time);atHome(s);assert.equal(s.missions.length,0);assert.equal(s.planets[0].ships.karawane,2);assert.equal(s.planets[0].ships.atlas,1);let bad=route(fixture());const old=structuredClone(bad);assert.throws(()=>act(bad,{type:'edit-route',id:bad.missions[0].id,fleet:{titan:1},stops:stops(),repeat:true},bad.time));assert.deepEqual(bad,old);assert.throws(()=>validateSave({...bad,missions:[{...bad.missions[0],fleet:{atlas:0}}]}));});
test('Cancel queue and depleted next-round fuel park all mixed ships exactly once',()=>{let s=route(fixture());const all=totals(s);s=act(s,{type:'edit-route',id:s.missions[0].id,name:'N',fleet:{atlas:1},stops:stops(),repeat:true},s.time);s=act(s,{type:'cancel-route-edit',id:s.missions[0].id},s.time);assert.equal(s.missions[0].pending,undefined);s.planets[0].resources.fuel=0;atHome(s);assert.equal(s.missions.length,0);assert.deepEqual(totals(s),all);const snapshot=structuredClone(s);advance(s,s.time+100000);assert.deepEqual(totals(s),totals(snapshot));});
test('Offline catch-up matches short updates, including a queued mixed-fleet switch',()=>{let s=route(fixture());s=act(s,{type:'edit-route',id:s.missions[0].id,name:'Offline',fleet:{atlas:2},stops:stops(0),repeat:true},s.time);const direct=structuredClone(s),stepped=structuredClone(s),end=s.time+3600000;advance(direct,end);for(let t=s.time+10000;t<end;t+=10000)advance(stepped,t);advance(stepped,end);assert.deepEqual(direct,stepped);validateSave(direct);});
test('Old single-class route without a manifest can be saved, edited and parked intact',()=>{let s=route(fixture(),{karawane:2});delete s.missions[0].fleet;s=validateSave(s);const all=totals(s);s=act(s,{type:'edit-route',id:s.missions[0].id,name:'Alt',fleet:{karawane:2},stops:stops(0),repeat:false},s.time);atHome(s);assert.equal(s.missions.length,0);assert.deepEqual(totals(s),all);});
