import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {RES,SHIPS,TECHS,vector,isFreighter} from '../src/config.js';
import {newGame,act,advance,shipInfo,cargoCapacity,legInfo,routeInfo} from '../src/engine.js';
import {validateSave,parseSave} from '../src/storage.js';
const zero=()=>vector([0,0,0]),max=()=>Object.fromEntries(RES.map(k=>[k,'max']));
const newShips=['kurier','karawane','atlas','arche','falke','waechter','donner','titan'];
function fixture(){const s=newGame('Schiffe',1800000000000),home=s.planets[0];home.buildings.warehouse=15;home.buildings.lab=5;home.buildings.shipyard=6;home.resources=vector([100000,100000,100000]);for(const [k,t] of Object.entries(TECHS))s.tech[k]=t.max;for(const k of RES)home.buildings[k]=0;home.ships.transport=4;const colony=structuredClone(home);Object.assign(colony,{id:'ferrum',name:'Ferrum',distance:2,resources:vector([8000,8000,8000])});s.planets.push(colony);return s;}
const step=s=>advance(s,Math.min(...s.missions.map(m=>m.due)));
const totals=s=>Object.fromEntries(RES.map(k=>[k,s.planets.reduce((a,p)=>a+p.resources[k]+p.depot[k],0)+s.missions.reduce((a,m)=>a+m.cargo[k],0)]));
test('All eight new classes charge their build costs, complete once and persist',()=>{for(const key of newShips){let s=fixture(),p=s.planets[0],old={...p.resources};s=act(s,{type:'ship',key,count:2},s.time);for(const [i,k] of RES.entries())assert.equal(s.planets[0].resources[k],old[k]-2*SHIPS[key].cost[i]);s=advance(s,s.planets[0].shipjob.end);assert.equal(s.planets[0].ships[key],2);s=parseSave(JSON.stringify(s));advance(s,s.time+1);assert.equal(s.planets[0].ships[key],2);}});
test('Shipyard, class research and drive gates reject atomically',()=>{for(const key of newShips){const sh=SHIPS[key],s=fixture();s.planets[0].buildings.shipyard=(sh.shipyard||1)-1;const before=JSON.stringify(s);assert.throws(()=>act(s,{type:'ship',key,count:1},s.time),/Schiffswerft/);assert.equal(JSON.stringify(s),before);s.planets[0].buildings.shipyard=6;s.tech[sh.tech]=(sh.techLevel||1)-1;assert.match(shipInfo(s,s.planets[0],key).reason,/Stufe/);if(sh.driveLevel){s.tech[sh.tech]=TECHS[sh.tech].max;s.tech.drive=sh.driveLevel-1;assert.match(shipInfo(s,s.planets[0],key).reason,/Antrieb/);}}});
test('Freighter capacities and actual flight speed/fuel differ by class',()=>{const s=fixture(),[a,b]=s.planets;assert.ok(cargoCapacity(s,1,'arche')>cargoCapacity(s,1,'atlas'));assert.equal(cargoCapacity(s,1,'titan'),0);assert.ok(legInfo(s,a,b,1,'kurier').ms<legInfo(s,a,b,1,'arche').ms);assert.ok(legInfo(s,a,b,1,'arche').fuel>legInfo(s,a,b,1,'kurier').fuel);assert.ok(legInfo(s,a,b,1,'arche').fuel/cargoCapacity(s,1,'arche')<legInfo(s,a,b,1,'kurier').fuel/cargoCapacity(s,1,'kurier'));});
test('Every new freighter can deliver, collect and run a route without material or ship loss',()=>{for(const ship of newShips.filter(isFreighter)){let s=fixture();s.planets[0].ships[ship]=2;const before=totals(s),fuel=legInfo(s,s.planets[0],s.planets[1],1,ship).fuel*2;s=act(s,{type:'deliver',ship,to:'ferrum',count:1,order:vector([1000,0,0])},s.time);s=step(s);s=step(s);assert.equal(s.planets[0].ships[ship],2);assert.deepEqual(totals(s),{...before,fuel:before.fuel-fuel});s=act(s,{type:'collect',ship,to:'ferrum',count:1,order:max()},s.time);s=step(s);assert.equal(RES.reduce((a,k)=>a+s.missions[0].cargo[k],0),Math.min(cargoCapacity(s,1,ship),24000+1000));s=step(s);assert.equal(s.planets[0].ships[ship],2);const stops=[{planet:'home',load:vector([100,0,0]),unload:max()},{planet:'ferrum',load:vector([0,100,0]),unload:max()}];const f=routeInfo(s,stops,1,ship),old=totals(s);s=act(s,{type:'route',ship,count:1,stops,repeat:false},s.time);s=parseSave(JSON.stringify(s));s=step(s);s=step(s);assert.deepEqual(totals(s),{...old,fuel:old.fuel-f.fuel});assert.equal(s.planets[0].ships[ship],2);}});
test('New warships station permanently and cannot deliver cargo or operate routes',()=>{for(const ship of newShips.filter(k=>!isFreighter(k))){let s=fixture();s.planets[0].ships[ship]=2;const before=JSON.stringify(s);assert.throws(()=>act(s,{type:'deliver',ship,count:1,to:'ferrum',order:max()},s.time),/Transporter/);assert.throws(()=>act(s,{type:'station',ship,count:1,to:'ferrum',order:vector([1,0,0])},s.time),/Transporter/);assert.equal(JSON.stringify(s),before);s=act(s,{type:'station',ship,count:2,to:'ferrum'},s.time);s=parseSave(JSON.stringify(s));s=step(s);assert.equal(s.planets[1].ships[ship],2);assert.equal(s.planets[0].ships[ship],0);assert.equal(s.missions.length,0);}});
test('Version-one migration preserves legacy ships, shipbuilding and underway transport',()=>{let s=fixture();s=act(s,{type:'transport',to:'ferrum',count:1,cargo:vector([100,0,0])},s.time);s=act(s,{type:'ship',key:'transport',count:2},s.time);delete s.tech.military;for(const p of s.planets)for(const key of newShips)delete p.ships[key];const m=structuredClone(s.missions[0]),job=structuredClone(s.planets[0].shipjob);s=validateSave(s);assert.equal(s.tech.military,0);for(const key of newShips)assert.equal(s.planets[0].ships[key],0);assert.deepEqual(s.missions[0],m);assert.deepEqual(s.planets[0].shipjob,job);advance(s,s.time+100000);assert.equal(s.planets[0].ships.transport,6);});
test('Explicit malformed new ship counts, military levels and oversized cargo are rejected',()=>{let s=fixture();s.planets[0].ships.titan=-1;assert.throws(()=>validateSave(s));s=fixture();s.tech.military=null;assert.throws(()=>validateSave(s));s=fixture();s.planets[0].ships.kurier=1;s=act(s,{type:'station',ship:'kurier',to:'ferrum',count:1},s.time);s.missions[0].cargo.metal=cargoCapacity(s,1,'kurier')+1;assert.throws(()=>validateSave(s));});
test('Leaderboard migration costs match every ship and technology in the game',()=>{const sql=readFileSync('supabase/ship-tiers.sql','utf8'),all=readFileSync('supabase/leaderboard.sql','utf8');const costs=JSON.parse(sql.match(/costs constant jsonb := '(.*?)'::jsonb/s)[1]);for(const [key,sh] of Object.entries(SHIPS))assert.deepEqual(costs.ships[key],sh.cost,key);for(const [key,t] of Object.entries(TECHS))assert.deepEqual(costs.tech[key],t.cost,key);assert.ok(all.includes(sql.slice(sql.indexOf('create or replace function'))));assert.match(sql,/when item.key='military' then 4/);});
