import {validateGalaxy} from './galaxy.js';
import {validateSave} from './storage.js';
export class CloudConflict extends Error {constructor(){super('Ein anderes Gerät hat einen neueren Spielstand gespeichert. Exportiere bei Bedarf deinen lokalen Stand und lade dann den Cloud-Stand.');this.name='CloudConflict';}}
// Client injected for tests. Saves use a database-side atomic revision check.
export function createCloud(client,redirectUrl,commandFunction='game-command'){
 let user=null,revision=0,loaded=false,busy=false,authoritative=false,pvp=null,receivedAt=0,pending=null;
 async function perform(request){const result=await client.functions.invoke(commandFunction,{body:request});if(result.error){let message=result.error.message;try{message=(await result.error.context?.json())?.error||message;}catch{}const failure=Error(message||'Spielserver nicht erreichbar.');failure.definitive=result.error.context?.status>=400&&result.error.context?.status<500;throw failure;}if(result.data?.error){const failure=Error(result.data.error);failure.definitive=true;throw failure;}const next=Number(result.data?.revision);if(!Number.isSafeInteger(next)||next<0||!result.data?.pvp)throw Error('Ungültige Serverantwort.');const state=result.data.state?validateSave(result.data.state):null;revision=next;pvp=result.data.pvp;receivedAt=Date.now();return {state,pvp};}
 const checked=result=>{if(result.error)throw result.error;return result.data;};
 return {
  get authoritative(){return authoritative;},get pvp(){return pvp;},get pending(){return pending;},get now(){return pvp?Math.max(pvp.serverNow,pvp.serverNow+Date.now()-receivedAt):Date.now();},get user(){return user;},get revision(){return revision;},get loaded(){return loaded;},
  async session(){const data=checked(await client.auth.getSession());user=data.session?.user||null;loaded=false;return user;},
  async signIn(email,password){if(busy)throw Error('Speicherung läuft noch.');const data=checked(await client.auth.signInWithPassword({email,password}));user=data.user;loaded=false;return user;},
  async signUp(email,password){return checked(await client.auth.signUp({email,password,options:{emailRedirectTo:redirectUrl}}));},
  async gameRequest(request={type:'sync'}){if(!user||!loaded||!authoritative)throw Error('Server-Spielstand zuerst laden.');if(busy)throw Error('Serverabgleich läuft noch.');const mutating=request.type!=='sync';if(mutating){const same=pending&&JSON.stringify({...pending,requestId:undefined})===JSON.stringify({...request,requestId:undefined});if(pending&&!same)throw Error('Bitte zuerst den offenen Auftrag in den Einstellungen erneut prüfen.');request=same?pending:{...request,requestId:crypto.randomUUID()};pending=request;}busy=true;try{const result=await perform(request);if(mutating)pending=null;return result;}catch(e){if(e.definitive){pending=null;throw e;}if(mutating){try{const result=await perform(request);pending=null;return result;}catch(retryError){if(retryError.definitive){pending=null;throw retryError;}}}throw e;}finally{busy=false;}},
  async createGame(name){if(!user||!loaded||!authoritative||revision!==0)throw Error('Neues Server-Spiel kann hier nicht erstellt werden.');return this.gameRequest({type:'new',name});},
  async signOut(){if(busy)throw Error('Speicherung läuft noch.');checked(await client.auth.signOut());user=null;revision=0;loaded=false;authoritative=false;pvp=null;pending=null;},
  async leaderboard(){if(!user)throw Error('Bitte anmelden, um die gemeinsame Rangliste zu sehen.');const result=await client.rpc('imperium_leaderboard');if(result.error){if(result.error.code==='PGRST202'||result.error.code==='42883')throw Error('Die Rangliste benötigt noch die einmalige Supabase-Erweiterung (supabase/leaderboard.sql).');throw result.error;}if(!Array.isArray(result.data))throw Error('Ungültige Ranglisten-Antwort.');return result.data;},
  async reports(filters={}){const r=await client.rpc('imperium_reports',{p_archived:filters.archived===null?null:!!filters.archived,p_kind:filters.kind||null,p_outcome:filters.outcome||null,p_search:filters.search||'',p_since:filters.since||null,p_offset:filters.offset||0,p_mission:filters.mission||null});if(r.error)throw r.error;if(!Array.isArray(r.data?.items)||!Number.isSafeInteger(r.data.total)||r.data.items.length>50)throw Error('Ungültige Berichtsantwort.');return r.data;},
  async archiveReports(ids,archived){const r=await client.rpc('imperium_archive_reports',{p_ids:ids,p_archived:archived});if(r.error)throw r.error;return r.data;},
  async galaxyView(){if(!user)throw Error('Bitte anmelden, um die gemeinsame Galaxie zu laden.');const result=await client.rpc('imperium_galaxy_view');if(result.error){if(['PGRST202','42883','42P01'].includes(result.error.code))throw Error('Die gemeinsame Galaxie benötigt die einmalige Supabase-Erweiterung (supabase/galaxy.sql).');throw result.error;}return validateGalaxy(result.data);},
  async galaxySync(action={}){if(authoritative){const result=await this.gameRequest(action.kind?{type:'galaxy',action}:{type:'sync'});return {...result,galaxy:await this.galaxyView()};}if(!user||!loaded)throw Error('Cloud-Spielstand zuerst laden.');if(busy)throw Error('Speicherung läuft noch.');busy=true;try{const result=await client.rpc('imperium_galaxy_sync',{p_expected:revision,p_kind:action.kind||null,p_from:action.from||null,p_to:action.to||null});if(result.error){if(result.error.message?.includes('SAVE_CONFLICT')){loaded=false;throw new CloudConflict();}throw result.error;}const next=Number(result.data?.revision);if(!Number.isSafeInteger(next)||next<revision||next>revision+1)throw Error('Ungültige Galaxie-Version.');const state=validateSave(result.data.state),galaxy=validateGalaxy(result.data.galaxy);revision=next;return {state,galaxy};}finally{busy=false;}},
  async load(){if(!user)throw Error('Bitte anmelden.');if(busy)throw Error('Speicherung läuft noch.');loaded=false;if(client.functions?.invoke){const status=await client.rpc('imperium_pvp_status');if(status.error&&!['PGRST202','42883'].includes(status.error.code))throw status.error;if(!status.error){if(status.data?.version!==1)throw Error('Unbekannte Serverversion.');authoritative=true;busy=true;try{const result=await perform({type:'sync'});loaded=true;return result.state;}finally{busy=false;}}authoritative=false;}
 const row=checked(await client.from('game_saves').select('state,revision').eq('user_id',user.id).maybeSingle());const state=row?validateSave(row.state):null;revision=row?Number(row.revision):0;if(!Number.isSafeInteger(revision)||revision<0)throw Error('Ungültige Cloud-Version.');loaded=true;return state;},
  async save(state){if(authoritative)throw Error('Server-Spielstände werden durch Spielaktionen gespeichert; Import ist gesperrt.');if(!user||!loaded)throw Error('Cloud-Spielstand zuerst laden.');if(busy)throw Error('Speicherung läuft noch.');const snapshot=validateSave(state);busy=true;try{const result=await client.rpc('save_imperium',{p_state:snapshot,p_expected:revision});if(result.error){if(result.error.message?.includes('SAVE_CONFLICT')){loaded=false;throw new CloudConflict();}throw result.error;}const next=Number(result.data);if(next!==revision+1)throw Error('Cloud-Speicherung lieferte keine gültige Bestätigung.');revision=next;return next;}finally{busy=false;}}
 };
}
export async function connectCloud(config){
 if(!config.enabled)return null;
 if(!/^https:\/\/[a-z0-9-]+\.supabase\.co\/?$/i.test(config.url)||!config.publishableKey)throw Error('Cloud-Konfiguration fehlt oder ist ungültig.');
 const {createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.117.2/+esm');
 return createCloud(createClient(config.url,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}),config.redirectUrl,config.commandFunction||'game-command');
}
