import {reportEscape} from './reports-ui.js';
const battleNumber=n=>Number(n||0).toLocaleString('de-DE',{maximumFractionDigits:2});
export function battleLogView(header,page=null,{round=0,offset=0}={}){
 const units=new Map(header.initial.map(u=>[u.id,u]));
 const label=id=>{const u=units.get(id);return (u?.name||u?.key||'Einheit')+' · '+id+(u?.commander?' · '+u.commander:'');};
 const control=(text,r,o=0,disabled=false)=>'<button data-battle-round="'+r+'" data-battle-offset="'+o+'" '+(disabled?'disabled':'')+' aria-pressed="'+(r===round&&o===offset)+'">'+text+'</button>';
 const nav=control('Start',0)+header.rounds.map(q=>control('Runde '+q.round,q.round)).join('')+control('Ende',-1);
 const reason={bonus:'Passendes Bonusziel',military:'Kriegsschiff hat Vorrang',defense:'Orbitale Verteidigung hat Vorrang',civil:'Keine Kriegsschiffe oder Verteidigungen übrig'};
 const summaries=header.rounds.map(q=>'<tr><th scope="row">'+q.round+'</th><td>'+q.after.attacker.count+'</td><td>'+q.after.defender.count+'</td></tr>').join('');
 const initial={attacker:header.initial.filter(u=>u.side==='attacker').length,defender:header.initial.filter(u=>u.side==='defender').length};
 const after=round===0?Object.fromEntries(Object.entries(initial).map(([side,count])=>[side,{count}])):round===-1?header.rounds.at(-1)?.after||Object.fromEntries(Object.entries(initial).map(([side,count])=>[side,{count}])):page?.after;
 const board=after?'<div class="battle-board">'+['attacker','defender'].map(side=>'<section><h3>'+(side==='attacker'?'Angreifer':'Verteidiger')+(side===header.ownSide?' · Du':'')+'</h3><p>'+reportEscape(header.participants?.[side]||'Commander')+'</p><strong>'+after[side].count+' / '+initial[side]+' Einheiten</strong><progress max="'+Math.max(1,initial[side])+'" value="'+after[side].count+'" aria-label="Verbleibende '+side+'"></progress>'+(after[side].hp!==undefined?'<small>Hülle insgesamt: '+battleNumber(after[side].hp)+' · Schild: '+battleNumber(after[side].shield)+'</small>':'')+'</section>').join('')+'</div>':'';
 let body='',total=0;
 if(round<=0){const list=round===0?header.initial:header.final;total=list.length;body='<h3>'+(round===0?'Startzustand':'Endzustand')+' jeder Einheit</h3><div class="battle-units">'+list.slice(offset,offset+200).map(u=>'<article><strong>'+reportEscape(label(u.id))+'</strong><small>'+(u.side==='attacker'?'Angreifer':'Verteidiger')+' · '+reportEscape(u.category)+'</small><p>Hülle '+battleNumber(u.hp)+' / '+battleNumber(u.maxHp)+' · Schild '+battleNumber(u.shield)+' / '+battleNumber(u.maxShield)+'</p><progress max="'+u.maxHp+'" value="'+u.hp+'" aria-label="Hülle"></progress><small>Angriff '+battleNumber(u.attack)+' · '+u.shots+' Schuss/Schüsse</small></article>').join('')+'</div>';}
 else if(page){
  total=Math.max(page.shotTotal,page.impactTotal);
  body='<h3>Runde '+round+' · Gleichzeitig verrechneter Schaden</h3><p>Alle zu Rundenbeginn lebenden Einheiten schießen. Die Zeilenreihenfolge ist keine zeitliche Trefferfolge. Überzähliger Schaden wird nicht auf andere Ziele verteilt.</p><div class="battle-units">'+page.impacts.map(hit=>{const u=units.get(hit.target);return '<article class="'+(hit.destroyed?'battle-destroyed':'')+'"><strong>'+reportEscape(label(hit.target))+'</strong><p>'+battleNumber(hit.damage)+' Schaden erhalten</p><small>Schild absorbiert: '+battleNumber(hit.shieldDamage)+' · Hülle verloren: '+battleNumber(hit.hullDamage)+' · Überschaden: '+battleNumber(hit.overkill)+'</small><p>HP '+battleNumber(hit.hpBefore)+' → '+battleNumber(hit.hpAfter)+' · Schild '+battleNumber(hit.shieldBefore)+' → '+battleNumber(hit.shieldAfter)+'</p><progress max="'+(u?.maxHp||1)+'" value="'+hit.hpAfter+'" aria-label="Verbleibende Hülle"></progress>'+(hit.destroyed?'<strong>Zerstört am Rundenende</strong>':'')+'</article>';}).join('')+'</div><h3>Einzelne Schüsse · '+page.shotTotal+' insgesamt</h3><div class="battle-shot-table"><table><thead><tr><th>Schütze → Ziel</th><th>Berechnung</th><th>Zielwahl</th></tr></thead><tbody>'+page.shots.map(s=>'<tr><td>'+reportEscape(label(s.shooter))+'<br>→ '+reportEscape(label(s.target))+'<small>Schuss '+s.shot+'</small></td><td>'+battleNumber(s.base)+' × '+battleNumber(1+s.bonus)+' = <strong>'+battleNumber(s.damage)+'</strong></td><td>'+reportEscape(reason[s.reason]||s.reason)+'</td></tr>').join('')+'</tbody></table></div>';
 }
 body=(page?.summaryHTML||'')+'<details class="battle-raw-details"><summary>'+(round>0?'Einzelne Treffer und Schüsse anzeigen':'Einzelne Schiffe anzeigen')+'</summary>'+body+'</details>';
 const pages=total>200?'<div class="battle-pages">'+control('← Vorherige Seite',round,Math.max(0,offset-200),offset===0)+'<span>Einträge '+(offset+1)+'–'+Math.min(total,offset+200)+' / '+total+'</span>'+control('Nächste Seite →',round,offset+200,offset+200>=total)+'</div>':'';
 return '<h2>Kampfprotokoll · Regelversion '+header.ruleVersion+'</h2><p>'+reportEscape(header.from)+' → '+reportEscape(header.to)+'</p><p>Bonusziele zuerst; danach Kriegsschiffe, Verteidigung und zivile Schiffe. Frachter und zivile Schiffe sind geschützt, solange auf ihrer Seite Kriegsschiffe leben.</p><div class="battle-round-nav">'+nav+'</div>'+board+pages+body+pages+'<details><summary>Forschung und Reproduzierbarkeit</summary><p>Seed: <code>'+reportEscape(header.seed)+'</code></p>'+['attacker','defender'].map(side=>'<p>'+(side==='attacker'?'Angreifer':'Verteidiger')+': Waffen '+(header.tech[side].weapons||0)+' · Schilde '+(header.tech[side].shields||0)+' · Panzerung '+(header.tech[side].armor||0)+' · Schildbereitschaft '+battleNumber(100*header.shieldFactors[side])+' %</p>').join('')+'</details><details><summary>Überlebende je Runde</summary><table><thead><tr><th>Runde</th><th>Angreifer</th><th>Verteidiger</th></tr></thead><tbody>'+summaries+'</tbody></table></details>';
}
