import {SHIPS,RES} from './config.js';
import {COMBAT,attackFlight,combatStats} from './combat.js';
const pvpEscape=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pvpDuration=n=>{n=Math.max(0,Math.ceil(n/1000));return Math.floor(n/60)+' Min '+n%60+' Sek';};
export function pvpSettings(pvp,busy=false,pending=false){
 if(!pvp)return '';
 return '<section class="panel"><h3>PvP '+(pvp.enabled?'aktiv':'pausiert')+'</h3><p>Eine Pause verhindert neue Angriffe. Laufende Kämpfe und Rückflüge werden weiter verarbeitet.</p>'+
 (pvp.isAdmin?'<button type="button" role="switch" aria-checked="'+pvp.enabled+'" data-action="pvp-toggle" '+(busy?'disabled':'')+'>'+(pvp.enabled?'PvP ausschalten':'PvP einschalten')+'</button>':'<p class="fine">Der PvP-Schalter ist nur für Administratoren verfügbar.</p>')+
 (pending?'<button type="button" data-action="pvp-retry">Offenen Auftrag erneut prüfen</button>':'')+'</section>';
}
export function pvpView(state,pvp,galaxy,busy=false,draft={}){
 if(!pvp)return '<section class="panel"><h2>PvP vorbereiten</h2><p>Das Kampfsystem benötigt die Server-Erweiterung. Nach der Installation findest du hier Angriffe, Warnungen und Berichte.</p></section>';
 const p=state.planets.find(p=>p.id===state.active),targets=(galaxy?.planets||[]).filter(p=>p.owner==='foreign'&&!p.reserved),now=pvp.serverNow;
 const protection=id=>pvp.colonies.find(p=>p.id===id)?.protectedUntil||0;
 const label=t=>'['+t.system+':'+t.slot+'] '+(t.surveyed?t.name:'Unbekannt')+' · '+t.commander;
 const incoming=pvp.incoming.map(m=>'<article class="notice"><strong>Angriff von '+pvpEscape(m.commander)+'</strong><p>Ziel '+pvpEscape(m.to)+' · Ankunft in <span data-due="'+m.arrival+'">'+pvpDuration(m.arrival-now)+'</span></p><p>Du kannst bis zur Ankunft Flotten verlegen, Ressourcen transportieren und Verteidigung fertigstellen.</p></article>').join('');
 const choices=Object.entries(SHIPS).filter(([,s])=>['military','freighter'].includes(s.category));
 const form=targets.length&&p.system?'<form id="pvp-attack-form"><label>Zielkolonie<select name="to">'+targets.map(t=>'<option value="'+t.id+'" '+(t.id===draft.to?'selected':'')+'>'+pvpEscape(label(t))+(protection(t.id)>now?' · Gründungsschutz':'')+'</option>').join('')+'</select></label><div class="pvp-manifest">'+choices.map(([k,s])=>'<label>'+pvpEscape(s.name)+' · verfügbar '+p.ships[k]+'<input name="'+k+'" type="number" min="0" max="'+Math.min(100,p.ships[k])+'" value="'+(draft[k]||0)+'" step="1"></label>').join('')+'</div><p id="pvp-estimate" class="fine">Flotte wählen: Das langsamste Schiff bestimmt die Flugzeit.</p><p class="fine">Mit einem Angriff endet der Gründungsschutz deiner Startkolonie. Maximal 25 % der plünderbaren Vorräte; innerhalb von 24 Stunden gilt zusätzlich ein gemeinsames Beutebudget je Zielkolonie.</p><button '+(!pvp.enabled||busy?'disabled':'')+'>Angriff losschicken</button></form>':'<p>Wähle als Start eine eigene gemeinsame Kolonie. Für Angriffe werden fremde besiedelte Kolonien benötigt.</p>';
 const outgoing=pvp.outgoing.map(m=>'<article class="mission"><strong>'+pvpEscape(m.to)+' · '+(m.status==='outbound'?'Angriff unterwegs':'Rückflug')+'</strong><p>'+Object.entries(m.fleet||{}).map(([k,n])=>n+' × '+pvpEscape(SHIPS[k].name)).join(', ')+'</p><span data-due="'+(m.status==='outbound'?m.arrival:m.returnAt)+'">'+pvpDuration((m.status==='outbound'?m.arrival:m.returnAt)-now)+'</span></article>').join('')||'<p class="muted">Keine Angriffsflotte unterwegs.</p>';
 const number=(v=0)=>Math.floor(v).toLocaleString('de-DE');
 const reports=pvp.reports.map(r=>'<details class="panel"><summary>'+pvpEscape(r.to)+' · '+({attacker:'Angreifer gewinnt',defender:'Verteidiger gewinnt',draw:'Unentschieden',cancelled:'Abgebrochen'}[r.outcome])+' · '+new Date(r.at).toLocaleString('de-DE')+'</summary>'+
 (r.reason?'<p>'+pvpEscape(r.reason)+'</p>':'<p>Angreifer übrig: '+Object.entries(r.attackerAfter).map(([k,n])=>n+' × '+pvpEscape(SHIPS[k].name)).join(', ')+'</p><p>Verteidiger übrig: '+(Object.entries(r.defenderAfter).filter(([,n])=>n).map(([k,n])=>n+' × '+pvpEscape(SHIPS[k].name)).join(', ')||'keine')+'</p><p>Beute M/K/T: '+RES.map(k=>number(r.loot[k])).join(' / ')+'</p><p>Geborgene Trümmer M/K: '+number(r.salvage.metal)+' / '+number(r.salvage.crystal)+'</p><p>Trümmer am Ziel M/K: '+number(r.debrisLeft.metal)+' / '+number(r.debrisLeft.crystal)+'</p><ol>'+r.rounds.map(q=>'<li>Runde '+q.round+': '+q.attacker+' Angreifer / '+q.defender+' Verteidiger</li>').join('')+'</ol>')+'</details>').join('')||'<p class="muted">Noch keine Kampfberichte.</p>';
 const stats=Object.keys(COMBAT).filter(k=>['military','defense'].includes(SHIPS[k].category)).map(k=>{const c=combatStats(k,state.tech);return '<tr><td>'+pvpEscape(SHIPS[k].name)+'</td><td>'+number(c.hp)+'</td><td>'+number(c.shield)+'</td><td>'+number(c.attack)+'</td></tr>';}).join('');
 return '<div class="page-heading"><span class="eyebrow">GEMEINSAME KOLONIEN</span><h1>PvP & Verteidigung</h1><p>24 Stunden Gründungsschutz. Tutorial-Welten bleiben sicher. Kämpfe werden zum Ankunftszeitpunkt nachgeholt.</p></div>'+incoming+'<section class="panel"><h2>'+(!pvp.enabled?'PvP pausiert':'Angriff planen')+'</h2>'+form+'</section><section class="panel"><h2>Deine Angriffsflotte</h2>'+outgoing+'</section><section><h2>Kampfberichte</h2>'+reports+'</section><section class="panel"><h2>Kampfwerte mit deiner Forschung</h2><div class="pvp-table"><table><thead><tr><th>Einheit</th><th>Hülle</th><th>Schild</th><th>Schaden/Runde</th></tr></thead><tbody>'+stats+'</tbody></table></div><p>Maximal sechs Runden. Gleichzeitiger Beschuss; Boni gelten je Zielklasse. Schilde laden nach einem Kampf innerhalb von fünf Minuten nach.</p><p>Orbitales Reparaturmaterial M/K: '+number(p.defenseSalvage?.metal)+' / '+number(p.defenseSalvage?.crystal)+'.</p><p>Beschädigte Einheiten auf dieser Welt können für 30 % ihrer Baukosten in Metall/Kristall, anteilig zum Hüllenschaden, repariert werden.</p><button data-action="pvp-repair" '+(busy||!Object.values(p.hulls||{}).some(a=>a.length)?'disabled':'')+'>Einheiten reparieren</button></section>';
}
export function pvpEstimate(state,galaxy,to,fleet){
 const target=galaxy?.planets.find(p=>p.id===to),system=galaxy?.systems.find(s=>s.id===target?.system);
 if(!target||!system)throw Error('Ziel fehlt.');
 const f=attackFlight(state,state.planets.find(p=>p.id===state.active),{...system,slot:target.slot},fleet);
 return pvpDuration(f.ms)+' je Strecke · '+f.fuel+' Treibstoff insgesamt · langsamstes Schiff: '+SHIPS[f.slowest].name;
}
