import {RES,SHIPS,LABEL} from './config.js';
const socialEscape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const socialFleetText=f=>Object.entries(f||{}).map(([k,n])=>n+' × '+SHIPS[k].name).join(' · ')||'Keine';
const socialResourceText=c=>RES.filter(k=>c?.[k]).map(k=>c[k].toLocaleString('de-DE')+' '+LABEL[k]).join(' · ')||'Keine';
function socialRights(values={}){return '<div class="social-rights"><label><input type="checkbox" name="delivery" '+(values.delivery?'checked':'')+'> Lieferungen auf meine Galaxieplaneten erlauben</label><label><input type="checkbox" name="defense" '+(values.defense?'checked':'')+'> Verteidigungsflotten erlauben</label></div>';}
export function socialView(state,social,{busy=false,now=state.time,mode='deliver'}={}){
 if(!social)return '<section class="panel"><h2>Partnerschaften</h2><p>Für Partnerschaften muss der Spielserver mit partnerships.sql und der gemeinsamen game-command aktualisiert werden.</p></section>';
 const p=state.planets.find(p=>p.id===state.active),disabled=busy?'disabled':'',partners=social.partners.filter(p=>p.status==='accepted'),targets=partners.filter(p=>mode==='support'?p.received.defense:p.received.delivery&&(mode!=='trade-offer'||p.granted.delivery)).flatMap(p=>p.planets.map(q=>({...q,commander:p.name}))),category=mode==='support'?'military':'freighter';
 const rights=partners.map(p=>'<article class="panel"><h3>'+socialEscape(p.name)+'</h3><p class="fine">Du darfst: '+(p.received.delivery?'liefern':'keine Lieferungen')+' · '+(p.received.defense?'verteidigen':'keine Verteidigung')+'</p><form class="social-rights-form" data-op="permissions" data-id="'+p.id+'">'+socialRights(p.granted)+'<button '+disabled+'>Meine Freigaben speichern</button></form><button data-social-op="end" data-social-id="'+p.id+'" '+disabled+'>Partnerschaft beenden</button></article>').join('');
 const invites=social.partners.filter(p=>p.status==='pending').map(p=>'<article class="panel"><h3>'+socialEscape(p.name)+'</h3><p>'+ (p.incoming?'Möchte dein Partner werden.':'Deine Einladung wartet auf Zustimmung.')+'</p>'+(p.incoming?'<form class="social-rights-form" data-op="accept" data-id="'+p.id+'">'+socialRights()+'<button '+disabled+'>Einladung annehmen</button></form>':'')+'<button data-social-op="end" data-social-id="'+p.id+'" '+disabled+'>'+(p.incoming?'Ablehnen':'Einladung zurückziehen')+'</button></article>').join('');
 const fleetFields=Object.entries(SHIPS).filter(([k,s])=>s.category===category&&p.ships[k]>0).map(([k,s])=>'<label>'+socialEscape(s.name)+' · '+p.ships[k]+' verfügbar<input type="number" name="fleet-'+k+'" min="0" max="'+p.ships[k]+'" step="1" value="0"></label>').join('');
 const quantities=prefix=>'<div class="form-grid">'+RES.map(k=>'<label>'+LABEL[k]+'<input name="'+prefix+k+'" type="number" min="0" max="1000000000000" value="0" step="1" required></label>').join('')+'</div>';
 const missions=social.missions.map(m=>'<article class="panel"><h3>'+socialEscape(({support:'Verteidigung',delivery:'Lieferung',trade:'Rohstofftausch'})[m.kind])+' · '+socialEscape(m.own?m.hostName:m.commander)+'</h3><p>'+socialEscape(socialFleetText(m.fleet))+'</p><p>'+socialEscape(m.from)+' → '+socialEscape(m.to)+'</p><p>'+(m.status==='stationed'?'Bei deinem Partner stationiert':m.status==='returning'?'Rückflug':'Hinflug')+(m.status==='stationed'?'':' · <span data-due="'+m.due+'">'+Math.max(0,Math.ceil((m.due-now)/60000))+' Min</span>')+'</p>'+(m.kind==='support'&&['outbound','stationed'].includes(m.status)?'<button data-social-op="'+(m.own?'recall':'dismiss')+'" data-social-id="'+m.id+'" '+disabled+'>'+(m.own?'Eigene Flotte zurückrufen':'Verstärkung zurückschicken')+'</button>':'')+'</article>').join('')||'<p>Keine Partnerflotten unterwegs oder stationiert.</p>';
 const trades=social.trades.map(t=>'<article class="panel"><h3>Tausch mit '+socialEscape(t.name)+'</h3><p>Angebot: '+socialEscape(socialResourceText(t.cargo))+'</p><p>Gegenleistung: '+socialEscape(socialResourceText(t.payment))+'</p><p class="fine">Gültig bis '+socialEscape(new Date(t.expires).toLocaleTimeString('de-DE'))+'. Frachter und Waren werden erst bei Annahme gebunden.</p>'+(t.own?'':'<button data-social-op="trade-accept" data-social-id="'+t.id+'" '+disabled+'>Tausch verbindlich annehmen</button>')+'<button data-social-op="trade-cancel" data-social-id="'+t.id+'" '+disabled+'>'+(t.own?'Angebot zurückziehen':'Ablehnen')+'</button></article>').join('');
 return '<div class="page-heading"><h1>Partner & Unterstützung</h1><p>Freigaben gelten für gemeinsame Galaxiekolonien. Deine Schiffe bleiben dein Eigentum.</p></div><section class="panel"><h2>Commander einladen</h2><form id="social-invite-form"><label>Commander<select name="friend" required><option value="">Wählen …</option>'+social.players.map(q=>'<option value="'+q.id+'">'+socialEscape(q.name)+'</option>').join('')+'</select></label>'+socialRights()+'<button '+disabled+'>Einladung senden</button></form></section>'+invites+rights+'<section class="panel"><h2>Auftrag von '+socialEscape(p.name)+'</h2><div class="ship-categories">'+[['deliver','Liefern'],['support','Verteidigen'],['trade-offer','Direkter Tausch']].map(([key,title])=>'<button data-social-mode="'+key+'" aria-pressed="'+(mode===key)+'">'+title+'</button>').join('')+'</div>'+(!p.system?'<p>Wähle eine eigene Galaxiekolonie als Startplanet.</p>':!targets.length?'<p>Kein Partner hat die nötigen Rechte freigegeben.</p>':'<form id="social-flight-form" data-planet="'+p.id+'" data-op="'+mode+'"><label>Zielplanet<select name="to">'+targets.map(q=>'<option value="'+q.id+'">'+socialEscape(q.commander+' · '+q.name)+'</option>').join('')+'</select></label><fieldset><legend>'+(category==='military'?'Kriegsschiffe':'Frachter')+'</legend><div class="form-grid">'+(fleetFields||'<p>Keine passenden Schiffe verfügbar.</p>')+'</div></fieldset>'+(mode==='support'?'':'<h3>Deine Lieferung</h3>'+quantities('cargo-'))+(mode==='trade-offer'?'<h3>Gewünschte Gegenleistung</h3>'+quantities('payment-'):'')+'<p class="fine" id="social-estimate">Wähle deine Flotte. Es gelten normale Flugzeiten und Treibstoffkosten für Hin- und Rückflug.</p><p class="fine">'+(mode==='trade-offer'?'Der Partner muss zustimmen. Erst dann werden Ladung, Gegenleistung, Frachter und Treibstoff verbindlich reserviert. Deine Frachter liefern und bringen die Gegenleistung zurück.':'Verteidigungsflotten können jederzeit zurückgerufen oder vom Gastgeber zurückgeschickt werden. Frachter liefern und kehren zurück.')+'</p><button '+(busy||!fleetFields?'disabled':'')+'>'+(mode==='trade-offer'?'Tauschangebot senden':'Flotte starten')+'</button></form>')+'</section><section><h2>Offene Tauschgeschäfte</h2>'+(trades||'<p>Keine offenen Angebote.</p>')+'</section><section><h2>Partnerflotten</h2>'+missions+'</section>';
}
